name: Build & Release

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      version:
        description: 'Release version'
        required: true

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
    
    - name: "Checkout repository"
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        npm install

    - name: Build package
      run: |
        npm run build

    - name: Push new build
      uses: EndBug/add-and-commit@a3adef035a1381dcf888c90b847240e2ddb9e008
      with:
        author_name: Link-
        author_email: bassem@interop.link
        message: 'Update build'
        add: 'bin/starred_search'

    - name: Update version
      run: |
        npm version ${{ github.event.inputs.name }}

    - name: Push new version and tag
      uses: EndBug/add-and-commit@a3adef035a1381dcf888c90b847240e2ddb9e008
      with:
        author_name: Link-
        author_email: bassem@interop.link
        message: 'Update version'
        add: 'package.json'

    - name: Release
      uses: JS-DevTools/npm-publish@0f451a94170d1699fd50710966d48fb26194d939
      with:
        token: ${{ secrets.NPM_TOKEN }}
