name: Build & Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
    
    - name: "Checkout repository"
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        npm install

    - name: Build package
      run: |
        npm run build

    - name: Get tag name
      id: tag_extraction
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

    - name: Update version
      env:
        RELEASE_VERSION: ${{ steps.tag_extraction.outputs.tag }}
      run: |
        echo $RELEASE_VERSION
        npm version $RELEASE_VERSION --no-git-tag-version
        echo ${{ steps.tag_extraction.outputs.tag }}

    - name: Push changes and tags
      uses: EndBug/add-and-commit@a3adef035a1381dcf888c90b847240e2ddb9e008
      with:
        author_name: Link-
        author_email: bassem@interop.link
        message: 'Update version'
        add: '["package.json", "bin/starred_search"]'

    - name: Release
      uses: JS-DevTools/npm-publish@0f451a94170d1699fd50710966d48fb26194d939
      with:
        token: ${{ secrets.NPM_TOKEN }}
